FROM cd/bsv-bitcoin-sv:base

RUN ./autogen.sh

# No debug symbols but include optimization
RUN ./configure --with-incompatible-bdb CXXFLAGS='-O2'

RUN make V=1
RUN make install

FROM alpine:3.4

RUN apk update
RUN apk add boost-date_time boost-filesystem boost-program_options boost-system boost-thread
RUN apk add db ttf-ubuntu-font-family libevent

COPY --from=0 /usr/lib/libdb_cxx-5.3.so /usr/lib
COPY --from=0 /usr/local/bin/* /usr/local/bin/







